db_connection: "postgresql://debug:debug@database"
debug: false
score_turbulence: 0.5
initial_score: 1000
matchmaker:
  target_seconds_per_game: 10
  matchmakers: 2
gamemode:
  id: chess
  options:
    turn_time: 10
    player_turn_time: 300
    chess960: true
